### PR TITLE
fix: rename sqlite3.py to sqlite3_utils.py and correct imports - avoi…

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**
…d runtime errors

### CODE REVIEW

**Comment by penberg** [comment]
@Abdur-rahmaanJ What is the error you are seeing?

**Comment by Abdur-rahmaanJ** [comment]
Sorry, filling up

## Problem

I began experiencing sqlite errors on 3 python hosts,

1. Render.com

```
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/sqlalchemy_libsql/__init__.py", line 92, in import_dbapi
    from libsql_client import dbapi2 as libsql_client
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/libsql_client/dbapi2/__init__.py", line 16, in <module>
    from ._reexports import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/libsql_client/dbapi2/_reexports.py", line 76, in <module>
    from sqlite3.dbapi2 import (
ImportError: cannot import name 'SQLITE_BUSY_TIMEOUT' from 'sqlite3.dbapi2' (/usr/local/lib/python3.11/sqlite3/dbapi2.py)
```

2. koyeb.com, Python3.12

Selection_330

3. pythonanywhere.com, Python3.10

Selection_331

While searching for an answer i saw this SO post about [AttributeNotFound for SQLite](https://stackoverflow.com/questions/25705671/python-attributeerror-module-object-has-no-attribute-connect), with the issue being a file named sqlite3.py present in the target project.

Iit's never a good idea, irrespective of my issue to name a file the same as a module or package, happens often when people name their first Flask app, flask.py.

The project i was trying to deploy is this one: https://github.com/linkversity/linkversity

I contacted Render's support, they are as clueless as me.

So, @penberg hope it helps!

**Comment by Abdur-rahmaanJ** [comment]
@penberg You have an idea when this fix will be deployed?

**Comment by penberg** [comment]
@Abdur-rahmaanJ I just released 0.3.1 with this fix.

**Pull request merged**
